apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: motd-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: motd
    networking.knative.dev/visibility: cluster-local
spec:
  source:
    git:
      url: https://github.com/alexandreroman/motd-frontend.git
      ref:
        branch: main
  serviceClaims:
  - name: motd-config
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: motd-frontend-config
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
      cpu: 500m
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
      autoscaling.knative.dev/maxScale: "3"
      autoscaling.knative.dev/target: "20"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/window: "60s"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: node
